"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/lib/auth/auth-context";
import { errorMessage } from "@/lib/auth/api";
import type { JobOpening, JobStatus } from "@/lib/workspace-types";
import { EmptyState, LoadingState, Modal, Notice, PageHeader, StatusPill, formatDate, titleCase } from "@/components/workspace-ui";

const blank = { title: "", description: "", department: "", location: "", employmentType: "Full-time", experienceLevel: "MID_LEVEL", requiredSkills: "", preferredSkills: "", minExperienceYears: "", maxExperienceYears: "" };
type JobForm = typeof blank;

export default function JobsPage() {
  const { status, requestWithAuth } = useAuth();
  const [jobs, setJobs] = useState<JobOpening[]>([]);
  const [form, setForm] = useState<JobForm>(blank);
  const [editing, setEditing] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const data = await requestWithAuth<{ jobs: JobOpening[] }>("/jobs"); setJobs(data.jobs); } catch (caught) { setError(errorMessage(caught)); } finally { setLoading(false); } }, [requestWithAuth]);
  useEffect(() => { if (status !== "authenticated") return; const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load,status]);
  const update = (field: keyof JobForm, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const edit = async (id: string) => { setBusy(id); try { const data = await requestWithAuth<{ job: JobOpening }>(`/jobs/${id}`); const job = data.job; setForm({ title: job.title, description: job.description ?? "", department: job.department ?? "", location: job.location ?? "", employmentType: job.employmentType ?? "", experienceLevel: job.experienceLevel ?? "", requiredSkills: job.requiredSkills.join(", "), preferredSkills: job.preferredSkills.join(", "), minExperienceYears: job.minExperienceYears?.toString() ?? "", maxExperienceYears: job.maxExperienceYears?.toString() ?? "" }); setEditing(id); setOpen(true); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(""); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy("save"); setError(""); const payload = { title: form.title, description: form.description, department: form.department || null, location: form.location || null, employmentType: form.employmentType || null, experienceLevel: form.experienceLevel || null, requiredSkills: form.requiredSkills.split(",").map((v)=>v.trim()).filter(Boolean), preferredSkills: form.preferredSkills.split(",").map((v)=>v.trim()).filter(Boolean), minExperienceYears: form.minExperienceYears ? Number(form.minExperienceYears) : null, maxExperienceYears: form.maxExperienceYears ? Number(form.maxExperienceYears) : null }; try { await requestWithAuth(editing ? `/jobs/${editing}` : "/jobs", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); setNotice(editing ? "Job updated." : "Job opening created."); setOpen(false); setEditing(null); setForm(blank); await load(); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(""); } };
  const setStatus = async (job: JobOpening, next: JobStatus) => { setBusy(job.id); setError(""); try { await requestWithAuth(`/jobs/${job.id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); await load(); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(""); } };
  const remove = async (job: JobOpening) => { if (!confirm(`Delete ${job.title}?`)) return; setBusy(job.id); try { await requestWithAuth(`/jobs/${job.id}`, { method: "DELETE" }); setJobs((items) => items.filter((item) => item.id !== job.id)); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(""); } };
  const openCreate = () => { setEditing(null); setForm(blank); setOpen(true); };
  return <div><PageHeader eyebrow="Hiring foundation" title="Job openings" description="Create role briefs that anchor every generated interview and evaluation." action={<button className="solid-button" onClick={openCreate}>New job opening</button>}/>{(error||notice) && <div className="mt-6">{error ? <Notice>{error}</Notice> : <Notice tone="success">{notice}</Notice>}</div>}
    <section className="mt-8">{loading ? <LoadingState label="Loading job openings"/> : jobs.length === 0 ? <EmptyState title="Create your first job" description="Define the role, skills, and experience range before creating an interview." action={<button className="solid-button" onClick={openCreate}>Create job</button>}/> : <div className="grid gap-5 xl:grid-cols-2">{jobs.map((job,index)=><article key={job.id} className="workspace-card card-rise" style={{animationDelay:`${index*55}ms`}}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-slate-950">{job.title}</h2><StatusPill value={job.status}/></div><p className="mt-1 text-sm text-slate-500">{job.department || "General"} · {job.location || "Flexible"} · {job.employmentType || "Not specified"}</p></div><div className="flex flex-col items-end gap-2"><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600">{job._count?.interviews ?? 0} interviews</span><Link href="/recruiter/applications" className="text-xs font-bold text-violet-600">{job._count?.applications ?? 0} applications →</Link></div></div><div className="mt-5 flex flex-wrap gap-2">{job.requiredSkills.slice(0,6).map((skill)=><span key={skill} className="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-semibold text-violet-700">{skill}</span>)}</div><div className="mt-5 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-5"><button className="secondary-button" disabled={busy===job.id} onClick={()=>void edit(job.id)}>Edit</button>{job.status === "DRAFT" && <button className="soft-button" onClick={()=>void setStatus(job,"ACTIVE")}>Publish</button>}{job.status === "ACTIVE" && <button className="secondary-button" onClick={()=>void setStatus(job,"CLOSED")}>Close</button>}{job.status === "CLOSED" && <button className="secondary-button" onClick={()=>void setStatus(job,"ARCHIVED")}>Archive</button>}{job.status === "ARCHIVED" && <button className="secondary-button" onClick={()=>void setStatus(job,"DRAFT")}>Restore draft</button>}<button className="danger-button ml-auto" onClick={()=>void remove(job)}>Delete</button><span className="w-full text-xs text-slate-400">Updated {formatDate(job.updatedAt)} · {titleCase(job.experienceLevel ?? "Any level")}</span></div></article>)}</div>}</section>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing ? "Edit job opening" : "Create job opening"} description="Use a clear role brief so AI-generated questions stay relevant." wide><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label><span className="workspace-label">Job title</span><input className="workspace-input" value={form.title} onChange={(e)=>update("title",e.target.value)} required minLength={2}/></label><label><span className="workspace-label">Department</span><input className="workspace-input" value={form.department} onChange={(e)=>update("department",e.target.value)}/></label><label><span className="workspace-label">Location</span><input className="workspace-input" value={form.location} onChange={(e)=>update("location",e.target.value)}/></label><label><span className="workspace-label">Employment type</span><input className="workspace-input" value={form.employmentType} onChange={(e)=>update("employmentType",e.target.value)}/></label><label><span className="workspace-label">Experience level</span><select className="workspace-select" value={form.experienceLevel} onChange={(e)=>update("experienceLevel",e.target.value)}>{["FRESHER","JUNIOR","MID_LEVEL","SENIOR","LEAD"].map(v=><option key={v}>{v}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label><span className="workspace-label">Min years</span><input className="workspace-input" type="number" min="0" value={form.minExperienceYears} onChange={(e)=>update("minExperienceYears",e.target.value)}/></label><label><span className="workspace-label">Max years</span><input className="workspace-input" type="number" min="0" value={form.maxExperienceYears} onChange={(e)=>update("maxExperienceYears",e.target.value)}/></label></div></div><label><span className="workspace-label">Description</span><textarea className="workspace-textarea" value={form.description} onChange={(e)=>update("description",e.target.value)} required minLength={20}/></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="workspace-label">Required skills (comma-separated)</span><input className="workspace-input" value={form.requiredSkills} onChange={(e)=>update("requiredSkills",e.target.value)}/></label><label><span className="workspace-label">Preferred skills</span><input className="workspace-input" value={form.preferredSkills} onChange={(e)=>update("preferredSkills",e.target.value)}/></label></div><div className="flex justify-end"><button className="solid-button min-w-32" disabled={busy==="save"}>{busy==="save"?"Saving…":"Save job"}</button></div></form></Modal>
  </div>;
}
