services:
  postgres:
    image: postgres:18-alpine
    container_name: ai-interview-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  qdrant:
    image: qdrant/qdrant:v1.19.0
    container_name: ai-interview-qdrant

    restart: unless-stopped

    ports:
      - "127.0.0.1:6333:6333"

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
    name: ai-interview-postgres-data

  qdrant_data:
    name: ai-interview-qdrant-data
