"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/lib/auth/auth-context";
import { errorMessage } from "@/lib/auth/api";
import type { InterviewTemplate } from "@/lib/workspace-types";
import { EmptyState, LoadingState, Modal, Notice, PageHeader, StatusPill, titleCase } from "@/components/workspace-ui";

const blank = { name:"", description:"", type:"TECHNICAL", difficulty:"MEDIUM", durationMinutes:"45", questionCount:"10", includeResumeQuestions:true, includeJobQuestions:true, includeCodingQuestions:false, adaptiveFollowUpsEnabled:false, maxFollowUpQuestions:"3", systemPrompt:"" };
type TemplateForm = typeof blank;

export default function TemplatesPage() {
  const { status, requestWithAuth } = useAuth(); const [items,setItems]=useState<InterviewTemplate[]>([]); const [form,setForm]=useState<TemplateForm>(blank); const [editing,setEditing]=useState<string|null>(null); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{const data=await requestWithAuth<{templates:InterviewTemplate[]}>("/interview-templates");setItems(data.templates);}catch(caught){setError(errorMessage(caught));}finally{setLoading(false);}},[requestWithAuth]); useEffect(()=>{if(status!=="authenticated")return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load,status]);
  const update=<K extends keyof TemplateForm>(key:K,value:TemplateForm[K])=>setForm(current=>({...current,[key]:value}));
  const edit=async(id:string)=>{setBusy(id);try{const data=await requestWithAuth<{template:InterviewTemplate}>(`/interview-templates/${id}`);const t=data.template;setForm({name:t.name,description:t.description??"",type:t.type,difficulty:t.difficulty,durationMinutes:String(t.durationMinutes),questionCount:String(t.questionCount),includeResumeQuestions:t.includeResumeQuestions,includeJobQuestions:t.includeJobQuestions,includeCodingQuestions:t.includeCodingQuestions,adaptiveFollowUpsEnabled:t.adaptiveFollowUpsEnabled??false,maxFollowUpQuestions:String(t.maxFollowUpQuestions??3),systemPrompt:t.systemPrompt??""});setEditing(id);setOpen(true);}catch(caught){setError(errorMessage(caught));}finally{setBusy("");}};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy("save");setError("");const payload={...form,durationMinutes:Number(form.durationMinutes),questionCount:Number(form.questionCount),maxFollowUpQuestions:Number(form.maxFollowUpQuestions),description:form.description||null,systemPrompt:form.systemPrompt||null};try{await requestWithAuth(editing?`/interview-templates/${editing}`:"/interview-templates",{method:editing?"PATCH":"POST",body:JSON.stringify(payload)});setOpen(false);setEditing(null);setForm(blank);setNotice(editing?"Template updated.":"Template created.");await load();}catch(caught){setError(errorMessage(caught));}finally{setBusy("");}};
  const toggle=async(item:InterviewTemplate)=>{setBusy(item.id);try{await requestWithAuth(`/interview-templates/${item.id}/active`,{method:"PATCH",body:JSON.stringify({isActive:!item.isActive})});await load();}catch(caught){setError(errorMessage(caught));}finally{setBusy("");}};
  const remove=async(item:InterviewTemplate)=>{if(!confirm(`Delete ${item.name}?`))return;setBusy(item.id);try{await requestWithAuth(`/interview-templates/${item.id}`,{method:"DELETE"});setItems(current=>current.filter(entry=>entry.id!==item.id));}catch(caught){setError(errorMessage(caught));}finally{setBusy("");}};
  const create=()=>{setEditing(null);setForm(blank);setOpen(true);};
  return <div><PageHeader eyebrow="Interview design" title="Interview templates" description="Create consistent, reusable assessment blueprints with adaptive AI follow-ups." action={<button className="solid-button" onClick={create}>New template</button>}/>{(error||notice)&&<div className="mt-6">{error?<Notice>{error}</Notice>:<Notice tone="success">{notice}</Notice>}</div>}<section className="mt-8">{loading?<LoadingState label="Loading templates"/>:items.length===0?<EmptyState title="Design your first template" description="Choose question sources, difficulty, and interview length once, then reuse the blueprint." action={<button className="solid-button" onClick={create}>Create template</button>}/>:<div className="grid gap-5 xl:grid-cols-2">{items.map((item,index)=><article key={item.id} className="workspace-card card-rise" style={{animationDelay:`${index*55}ms`}}><div className="flex items-start justify-between gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-violet-100 text-violet-700"><svg viewBox="0 0 24 24" className="size-6" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 8h8M8 12h8M8 16h5"/></svg></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-950">{item.name}</h2><StatusPill value={item.isActive?"ACTIVE":"DISABLED"}/></div><p className="mt-1 text-sm text-slate-500">{titleCase(item.type)} · {titleCase(item.difficulty)} · {item.durationMinutes} min</p></div><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600">{item._count?.interviews??0} uses</span></div><p className="mt-5 line-clamp-2 text-sm leading-6 text-slate-500">{item.description||"No description provided."}</p><div className="mt-5 flex flex-wrap gap-2 text-xs">{item.includeResumeQuestions&&<span className="rounded-full bg-sky-50 px-2.5 py-1 font-semibold text-sky-700">Resume context</span>}{item.includeJobQuestions&&<span className="rounded-full bg-emerald-50 px-2.5 py-1 font-semibold text-emerald-700">Job context</span>}{item.includeCodingQuestions&&<span className="rounded-full bg-amber-50 px-2.5 py-1 font-semibold text-amber-700">Coding</span>}</div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-5"><button className="secondary-button" onClick={()=>void edit(item.id)} disabled={busy===item.id}>Edit</button><button className="soft-button" onClick={()=>void toggle(item)}>{item.isActive?"Disable":"Enable"}</button><button className="danger-button ml-auto" onClick={()=>void remove(item)}>Delete</button></div></article>)}</div>}</section>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit interview template":"Create interview template"} description="Define the structure AI uses to generate a consistent interview." wide><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label><span className="workspace-label">Template name</span><input className="workspace-input" value={form.name} onChange={e=>update("name",e.target.value)} required/></label><label><span className="workspace-label">Interview type</span><select className="workspace-select" value={form.type} onChange={e=>update("type",e.target.value)}>{["TECHNICAL","BEHAVIORAL","HR","MIXED"].map(v=><option key={v}>{v}</option>)}</select></label><label><span className="workspace-label">Difficulty</span><select className="workspace-select" value={form.difficulty} onChange={e=>update("difficulty",e.target.value)}>{["EASY","MEDIUM","HARD","ADAPTIVE"].map(v=><option key={v}>{v}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label><span className="workspace-label">Minutes</span><input className="workspace-input" type="number" min="5" max="240" value={form.durationMinutes} onChange={e=>update("durationMinutes",e.target.value)}/></label><label><span className="workspace-label">Questions</span><input className="workspace-input" type="number" min="1" max="100" value={form.questionCount} onChange={e=>update("questionCount",e.target.value)}/></label></div></div><label><span className="workspace-label">Description</span><textarea className="workspace-textarea" value={form.description} onChange={e=>update("description",e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2">{([['includeResumeQuestions','Resume-based questions'],['includeJobQuestions','Job-based questions'],['includeCodingQuestions','Coding questions'],['adaptiveFollowUpsEnabled','Adaptive follow-ups']] as const).map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-medium"><input type="checkbox" checked={form[key]} onChange={e=>update(key,e.target.checked)} className="size-4 accent-violet-600"/>{label}</label>)}</div>{form.adaptiveFollowUpsEnabled&&<label><span className="workspace-label">Maximum follow-ups</span><input className="workspace-input" type="number" min="0" max="10" value={form.maxFollowUpQuestions} onChange={e=>update("maxFollowUpQuestions",e.target.value)}/></label>}<label><span className="workspace-label">Custom system prompt (optional)</span><textarea className="workspace-textarea" value={form.systemPrompt} onChange={e=>update("systemPrompt",e.target.value)} placeholder="Additional guidance for question generation…"/></label><div className="flex justify-end"><button className="solid-button min-w-36" disabled={busy==="save"}>{busy==="save"?"Saving…":"Save template"}</button></div></form></Modal>
  </div>;
}
